// =============================================================================
// Farther Unified Platform — Event Bus
// =============================================================================
//
// Cloud Pub/Sub style event system for cross-platform communication.
// Stage 1: In-memory pub/sub with full event logging and replay.
// Stage 2: Google Cloud Pub/Sub with dead-letter topics and ordering keys.
//
// Events flow:
//   Data mutation → Event Bus → Subscribers
//     → Planning Engine (recompute projections)
//     → Proposal System (invalidate active proposals)
//     → HubSpot Sync (push CRM updates)
//     → Client Portal (real-time notifications)
//     → Audit Log (compliance trail)
//
// This module is self-contained — no React, Next.js, or Prisma dependencies.
//
// @module household/event-bus
// =============================================================================

// =====================================================================
// Event Type Enumeration
// =====================================================================

/**
 * Exhaustive enumeration of all household-related event types
 * that flow through the event bus.
 *
 * Naming convention: `{entity}.{action}` in lowercase with underscores.
 */
export type HouseholdEventType =
  // Household lifecycle
  | 'household.created'
  | 'household.updated'
  | 'household.deleted'
  | 'household.status_changed'
  // Member events
  | 'member.added'
  | 'member.updated'
  | 'member.removed'
  // Account events
  | 'account.added'
  | 'account.updated'
  | 'account.removed'
  | 'account.balance_changed'
  | 'account.connected'
  // Income events
  | 'income.added'
  | 'income.updated'
  | 'income.removed'
  // Expense events
  | 'expense.added'
  | 'expense.updated'
  | 'expense.removed'
  // Goal events
  | 'goal.added'
  | 'goal.updated'
  | 'goal.removed'
  | 'goal.status_changed'
  // Debt events
  | 'debt.added'
  | 'debt.updated'
  | 'debt.removed'
  // Real estate events
  | 'real_estate.added'
  | 'real_estate.updated'
  | 'real_estate.removed'
  // Tax & estate events
  | 'tax_profile.updated'
  | 'estate_plan.updated'
  // Planning events
  | 'plan.created'
  | 'plan.updated'
  | 'plan.calculated'
  // Proposal events
  | 'proposal.created'
  | 'proposal.accepted'
  | 'proposal.rejected'
  // Integration events
  | 'custodian.sync_completed'
  | 'hubspot.sync_completed'
  // Review events
  | 'review.scheduled'
  | 'review.completed'
  // Scenario events (Phase 5A)
  | 'scenario.created'
  | 'scenario.updated'
  | 'scenario.calculated'
  | 'scenario.recommended'
  | 'scenario.archived'
  | 'scenario.comparison_created';

// =====================================================================
// Event Schema
// =====================================================================

/**
 * The canonical event envelope for all household events.
 *
 * Every event carries a typed payload, provenance metadata, and
 * correlation/causation IDs for distributed tracing.
 *
 * @typeParam T - The shape of the event payload (defaults to unknown)
 */
export interface HouseholdEvent<T = unknown> {
  /** Unique identifier for this event (generated by the bus). */
  eventId: string;
  /** The type of event (determines how the payload is interpreted). */
  eventType: HouseholdEventType;
  /** The household this event pertains to. */
  householdId: string;
  /** The firm that owns the household. */
  firmId: string;
  /** The advisor assigned to the household. */
  advisorId: string;
  /** ISO 8601 timestamp when the event was created. */
  timestamp: string;
  /** The system or user type that originated the event. */
  source: 'ADVISOR' | 'CUSTODIAN' | 'CLIENT_PORTAL' | 'SYSTEM' | 'IMPORT';
  /** The user who triggered the event. */
  actor: {
    /** UUID of the user. */
    userId: string;
    /** Role of the user (ADMIN, ADVISOR, CLIENT, etc.). */
    role: string;
  };
  /** The event-specific data payload. */
  payload: T;
  /** Metadata for distributed tracing, versioning, and retry tracking. */
  metadata: {
    /** Correlation ID for grouping related events across a workflow. */
    correlationId: string;
    /** Causation ID: the eventId of the event that caused this one, or null. */
    causationId: string | null;
    /** Schema version of the event payload. */
    version: number;
    /** Number of times this event has been retried (0 = first attempt). */
    retryCount: number;
  };
}

// =====================================================================
// Dead Letter Record
// =====================================================================

/**
 * A record of a failed event handler invocation.
 * In Stage 2, these would be published to a dead-letter topic.
 */
export interface DeadLetterRecord {
  /** The event that failed to be processed. */
  event: HouseholdEvent;
  /** The error message from the failed handler. */
  error: string;
  /** The name/identifier of the handler that failed. */
  handlerName: string;
  /** ISO 8601 timestamp of the failure. */
  failedAt: string;
}

// =====================================================================
// Handler Types
// =====================================================================

/**
 * An event handler function that processes a household event.
 * Can be synchronous or asynchronous.
 */
export type EventHandler = (event: HouseholdEvent) => void | Promise<void>;

/**
 * Internal subscription record with metadata for debugging.
 */
interface Subscription {
  /** The event type this subscription listens for ('*' = wildcard). */
  eventType: HouseholdEventType | '*';
  /** The handler function to invoke. */
  handler: EventHandler;
  /** Optional human-readable name for the subscriber (for dead-letter logging). */
  subscriberName: string;
  /** ISO 8601 timestamp when the subscription was created. */
  subscribedAt: string;
}

// =====================================================================
// ID Generation
// =====================================================================

/** Counter for generating unique event IDs within a session. */
let eventIdCounter = 0;

/**
 * Generates a unique event identifier.
 * Combines timestamp, counter, and randomness for uniqueness.
 */
function generateEventId(): string {
  eventIdCounter++;
  const timestamp = Date.now().toString(36);
  const counter = eventIdCounter.toString(36).padStart(6, '0');
  const random = Math.random().toString(36).substring(2, 8);
  return `hevt_${timestamp}_${counter}_${random}`;
}

/**
 * Generates a unique correlation ID for grouping related events.
 */
function generateCorrelationId(): string {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 10);
  return `corr_${timestamp}_${random}`;
}

// =====================================================================
// Event Bus Implementation
// =====================================================================

/**
 * In-memory event bus implementing a pub/sub pattern for household events.
 *
 * Features:
 * - Type-safe event publishing and subscription
 * - Wildcard subscriptions ('*') for global listeners
 * - Full event log for audit and replay
 * - Dead-letter queue for failed handler invocations
 * - Correlation/causation tracking for distributed tracing
 * - Event replay by household ID
 *
 * This class is not exported directly — consumers use the singleton
 * {@link eventBus} instance.
 */
class EventBus {
  /** Ordered log of all published events. */
  private eventLog: HouseholdEvent[] = [];

  /** Active subscriptions keyed by event type. */
  private subscriptions: Map<HouseholdEventType | '*', Subscription[]> =
    new Map();

  /** Log of handler failures for debugging and monitoring. */
  private deadLetterQueue: DeadLetterRecord[] = [];

  /** Maximum number of events to retain in the in-memory log. */
  private readonly maxEventLogSize: number = 10_000;

  /** Maximum number of dead-letter records to retain. */
  private readonly maxDeadLetterSize: number = 1_000;

  // -------------------- Subscribe --------------------

  /**
   * Subscribe to events of a specific type or all events (wildcard).
   *
   * @param eventType - The event type to listen for, or '*' for all events
   * @param handler - The callback function to invoke when a matching event is published
   * @param subscriberName - Optional human-readable name for debugging and dead-letter logs
   * @returns An unsubscribe function that removes this subscription
   *
   * @example
   * ```ts
   * const unsub = eventBus.subscribe('account.balance_changed', async (event) => {
   *   console.log('Balance changed:', event.payload);
   * }, 'PortfolioRebalancer');
   *
   * // Later, to stop listening:
   * unsub();
   * ```
   */
  subscribe(
    eventType: HouseholdEventType | '*',
    handler: EventHandler,
    subscriberName?: string
  ): () => void {
    const subscription: Subscription = {
      eventType,
      handler,
      subscriberName: subscriberName ?? `anonymous_${Date.now()}`,
      subscribedAt: new Date().toISOString(),
    };

    const existing = this.subscriptions.get(eventType) ?? [];
    existing.push(subscription);
    this.subscriptions.set(eventType, existing);

    // Return unsubscribe function
    return () => {
      const subs = this.subscriptions.get(eventType);
      if (subs) {
        const idx = subs.indexOf(subscription);
        if (idx !== -1) {
          subs.splice(idx, 1);
        }
        if (subs.length === 0) {
          this.subscriptions.delete(eventType);
        }
      }
    };
  }

  // -------------------- Publish --------------------

  /**
   * Publish an event to the bus.
   *
   * Generates the eventId, timestamp, and metadata automatically.
   * All matching subscribers (type-specific + wildcard) are invoked.
   * Failed handlers are caught and logged to the dead-letter queue
   * without interrupting other subscribers.
   *
   * @param params - The event data (without auto-generated fields)
   * @returns The fully hydrated HouseholdEvent that was published
   *
   * @example
   * ```ts
   * const event = eventBus.publish({
   *   eventType: 'household.created',
   *   householdId: 'hh-001',
   *   firmId: 'firm-001',
   *   advisorId: 'adv-001',
   *   source: 'ADVISOR',
   *   actor: { userId: 'user-001', role: 'ADVISOR' },
   *   payload: { name: 'The Smith Family' },
   * });
   * ```
   */
  publish<T = unknown>(
    params: Omit<HouseholdEvent<T>, 'eventId' | 'timestamp' | 'metadata'> & {
      metadata?: Partial<HouseholdEvent<T>['metadata']>;
    }
  ): HouseholdEvent<T> {
    const event: HouseholdEvent<T> = {
      eventId: generateEventId(),
      eventType: params.eventType,
      householdId: params.householdId,
      firmId: params.firmId,
      advisorId: params.advisorId,
      timestamp: new Date().toISOString(),
      source: params.source,
      actor: params.actor,
      payload: params.payload,
      metadata: {
        correlationId:
          params.metadata?.correlationId ?? generateCorrelationId(),
        causationId: params.metadata?.causationId ?? null,
        version: params.metadata?.version ?? 1,
        retryCount: params.metadata?.retryCount ?? 0,
      },
    };

    // Append to event log (with size cap)
    this.eventLog.push(event as HouseholdEvent);
    if (this.eventLog.length > this.maxEventLogSize) {
      this.eventLog = this.eventLog.slice(-this.maxEventLogSize);
    }

    // Dispatch to subscribers
    this.dispatch(event as HouseholdEvent);

    return event;
  }

  /**
   * Publish a follow-up event caused by a prior event.
   * Automatically sets the causationId and correlationId for tracing.
   *
   * @param causingEvent - The event that triggered this new event
   * @param params - The new event data
   * @returns The fully hydrated follow-up HouseholdEvent
   */
  publishCaused<T = unknown>(
    causingEvent: HouseholdEvent,
    params: Omit<
      HouseholdEvent<T>,
      'eventId' | 'timestamp' | 'metadata'
    >
  ): HouseholdEvent<T> {
    return this.publish<T>({
      ...params,
      metadata: {
        correlationId: causingEvent.metadata.correlationId,
        causationId: causingEvent.eventId,
        version: 1,
        retryCount: 0,
      },
    });
  }

  // -------------------- Dispatch (internal) --------------------

  /**
   * Dispatches an event to all matching subscribers.
   * Handles async handlers and catches/logs any errors.
   */
  private dispatch(event: HouseholdEvent): void {
    const typeSubscribers = this.subscriptions.get(event.eventType) ?? [];
    const wildcardSubscribers = this.subscriptions.get('*') ?? [];
    const allSubscribers = [...typeSubscribers, ...wildcardSubscribers];

    for (const sub of allSubscribers) {
      try {
        const result = sub.handler(event);
        // If the handler returns a Promise, catch any async errors
        if (result && typeof result === 'object' && 'catch' in result) {
          (result as Promise<void>).catch((error: unknown) => {
            this.recordDeadLetter(event, sub.subscriberName, error);
          });
        }
      } catch (error: unknown) {
        this.recordDeadLetter(event, sub.subscriberName, error);
      }
    }
  }

  /**
   * Records a handler failure to the dead-letter queue.
   */
  private recordDeadLetter(
    event: HouseholdEvent,
    handlerName: string,
    error: unknown
  ): void {
    const record: DeadLetterRecord = {
      event,
      error: error instanceof Error ? error.message : String(error),
      handlerName,
      failedAt: new Date().toISOString(),
    };

    this.deadLetterQueue.push(record);
    if (this.deadLetterQueue.length > this.maxDeadLetterSize) {
      this.deadLetterQueue = this.deadLetterQueue.slice(-this.maxDeadLetterSize);
    }

    // In production, this would also log to an external monitoring service
    // console.error(`[EventBus] Dead letter: ${handlerName} failed for ${event.eventType}`, error);
  }

  // -------------------- Query Methods --------------------

  /**
   * Returns the full event log (newest last).
   * In Stage 2, this would query the event store / BigQuery.
   *
   * @returns An array of all recorded events
   */
  getEventLog(): HouseholdEvent[] {
    return [...this.eventLog];
  }

  /**
   * Returns events for a specific household, in chronological order.
   *
   * @param householdId - The household to filter events for
   * @returns An array of events for the given household
   */
  getEventsForHousehold(householdId: string): HouseholdEvent[] {
    return this.eventLog.filter((e) => e.householdId === householdId);
  }

  /**
   * Returns events matching a specific event type.
   *
   * @param eventType - The event type to filter for
   * @returns An array of matching events
   */
  getEventsByType(eventType: HouseholdEventType): HouseholdEvent[] {
    return this.eventLog.filter((e) => e.eventType === eventType);
  }

  /**
   * Returns events within a time range.
   *
   * @param from - ISO 8601 start timestamp (inclusive)
   * @param to - ISO 8601 end timestamp (inclusive)
   * @returns An array of events within the range
   */
  getEventsByTimeRange(from: string, to: string): HouseholdEvent[] {
    const fromDate = new Date(from);
    const toDate = new Date(to);
    return this.eventLog.filter((e) => {
      const eventDate = new Date(e.timestamp);
      return eventDate >= fromDate && eventDate <= toDate;
    });
  }

  /**
   * Returns all events sharing a correlation ID (i.e., part of the same workflow).
   *
   * @param correlationId - The correlation ID to search for
   * @returns An array of correlated events
   */
  getCorrelatedEvents(correlationId: string): HouseholdEvent[] {
    return this.eventLog.filter(
      (e) => e.metadata.correlationId === correlationId
    );
  }

  /**
   * Returns the total number of active subscriptions.
   *
   * @returns The sum of all subscription counts across all event types
   */
  getSubscriberCount(): number {
    let count = 0;
    this.subscriptions.forEach((subs) => {
      count += subs.length;
    });
    return count;
  }

  /**
   * Returns a breakdown of subscriber counts by event type.
   *
   * @returns A map of event type to subscriber count
   */
  getSubscriberBreakdown(): Map<HouseholdEventType | '*', number> {
    const breakdown = new Map<HouseholdEventType | '*', number>();
    this.subscriptions.forEach((subs, type) => {
      breakdown.set(type, subs.length);
    });
    return breakdown;
  }

  /**
   * Returns the dead-letter queue contents for monitoring.
   *
   * @returns An array of all recorded dead-letter entries
   */
  getDeadLetterQueue(): DeadLetterRecord[] {
    return [...this.deadLetterQueue];
  }

  /**
   * Returns the number of events in the event log.
   *
   * @returns The event log size
   */
  getEventLogSize(): number {
    return this.eventLog.length;
  }

  // -------------------- Replay --------------------

  /**
   * Replays all events for a specific household through a handler.
   *
   * This is useful for rebuilding state (event sourcing) or
   * for new subscribers that need to catch up on historical events.
   *
   * @param householdId - The household whose events should be replayed
   * @param handler - The handler to invoke for each replayed event
   *
   * @example
   * ```ts
   * eventBus.replayEvents('hh-001', (event) => {
   *   projectionStore.apply(event);
   * });
   * ```
   */
  replayEvents(householdId: string, handler: EventHandler): void {
    const events = this.getEventsForHousehold(householdId);
    for (const event of events) {
      try {
        const result = handler(event);
        if (result && typeof result === 'object' && 'catch' in result) {
          (result as Promise<void>).catch((error: unknown) => {
            this.recordDeadLetter(event, 'replay_handler', error);
          });
        }
      } catch (error: unknown) {
        this.recordDeadLetter(event, 'replay_handler', error);
      }
    }
  }

  /**
   * Replays events of a specific type through a handler.
   *
   * @param eventType - The event type to replay
   * @param handler - The handler to invoke for each replayed event
   */
  replayEventsByType(
    eventType: HouseholdEventType,
    handler: EventHandler
  ): void {
    const events = this.getEventsByType(eventType);
    for (const event of events) {
      try {
        const result = handler(event);
        if (result && typeof result === 'object' && 'catch' in result) {
          (result as Promise<void>).catch((error: unknown) => {
            this.recordDeadLetter(event, 'replay_type_handler', error);
          });
        }
      } catch (error: unknown) {
        this.recordDeadLetter(event, 'replay_type_handler', error);
      }
    }
  }

  // -------------------- Administration --------------------

  /**
   * Removes all subscriptions.
   * Intended for use in test suites and during graceful shutdown.
   */
  clearSubscribers(): void {
    this.subscriptions.clear();
  }

  /**
   * Removes all events from the event log.
   * Intended for use in test suites only.
   */
  clearEventLog(): void {
    this.eventLog = [];
  }

  /**
   * Clears the dead-letter queue.
   * Intended for use in test suites or after manual review.
   */
  clearDeadLetterQueue(): void {
    this.deadLetterQueue = [];
  }

  /**
   * Resets the entire event bus state (subscriptions, log, dead letters).
   * Intended for use in test suites only.
   */
  reset(): void {
    this.clearSubscribers();
    this.clearEventLog();
    this.clearDeadLetterQueue();
  }
}

// =====================================================================
// Singleton Export
// =====================================================================

/**
 * Global event bus instance for the application.
 *
 * All modules should import and use this singleton rather than
 * creating their own EventBus instances.
 *
 * @example
 * ```ts
 * import { eventBus } from '@/lib/household/event-bus';
 *
 * // Subscribe to events
 * eventBus.subscribe('household.created', (event) => {
 *   syncToHubSpot(event);
 * }, 'HubSpotSync');
 *
 * // Publish an event
 * eventBus.publish({
 *   eventType: 'household.created',
 *   householdId: 'hh-001',
 *   firmId: 'firm-001',
 *   advisorId: 'adv-001',
 *   source: 'ADVISOR',
 *   actor: { userId: 'user-001', role: 'ADVISOR' },
 *   payload: { name: 'The Smith Family' },
 * });
 * ```
 */
export const eventBus = new EventBus();

// Re-export the class type for testing (the class itself is not exported)
export type { EventBus as EventBusType };
