import { ProviderStrategy } from './types';

export const PROVIDERS: Record<string, ProviderStrategy> = {
  // ─── AQR (Track A / E) ─────────────────────────────────────────────
  aqr_145_45: {
    id: 'aqr_145_45',
    provider: 'AQR',
    name: 'AQR Flex 145/45',
    shortName: '145/45',
    formulaTrack: 'A',
    longRatio: 1.45,
    shortRatio: 0.45,
    grossMultiplier: 1.90,
    fees: {
      mgmtFee: 0.0075,
      mgmtFeeEditable: false,
      preTaxFinancingCost: 0.005,
      postTaxFinancingCost: 0.003,
      txnCosts: 0.001,
    },
    alpha: { longAlpha: 0.005, shortAlpha: 0.005 },
    cncl: { cnclBase: 0.12, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 5_000_000,
    qualifiedPurchaserRequired: true,
  },
  aqr_250_150: {
    id: 'aqr_250_150',
    provider: 'AQR',
    name: 'AQR Flex 250/150',
    shortName: '250/150',
    formulaTrack: 'A',
    longRatio: 2.50,
    shortRatio: 1.50,
    grossMultiplier: 4.00,
    fees: {
      mgmtFee: 0.0085,
      mgmtFeeEditable: false,
      preTaxFinancingCost: 0.008,
      postTaxFinancingCost: 0.005,
      txnCosts: 0.0015,
    },
    alpha: { longAlpha: 0.005, shortAlpha: 0.005 },
    cncl: { cnclBase: 0.18, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 5_000_000,
    qualifiedPurchaserRequired: true,
  },
  aqr_delphi_plus: {
    id: 'aqr_delphi_plus',
    provider: 'AQR',
    name: 'AQR Delphi+',
    shortName: 'Delphi+',
    formulaTrack: 'E',
    longRatio: 2.50,
    shortRatio: 1.50,
    grossMultiplier: 4.00,
    fees: {
      mgmtFee: 0.01,
      mgmtFeeEditable: false,
      preTaxFinancingCost: 0.008,
      postTaxFinancingCost: 0.005,
      txnCosts: 0.002,
    },
    alpha: { longAlpha: 0.007, shortAlpha: 0.007 },
    cncl: { cnclBase: 0.20, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'ordinary_income',
    minimumInvestment: 5_000_000,
    qualifiedPurchaserRequired: true,
    notes: 'Tax losses offset ordinary income (Track E)',
  },

  // ─── Quantinno (Track A) ───────────────────────────────────────────
  quantinno_200_100: {
    id: 'quantinno_200_100',
    provider: 'Quantinno',
    name: 'Quantinno 200/100',
    shortName: '200/100',
    formulaTrack: 'A',
    longRatio: 2.00,
    shortRatio: 1.00,
    grossMultiplier: 3.00,
    fees: {
      mgmtFee: 0.008,
      mgmtFeeEditable: false,
      preTaxFinancingCost: 0.006,
      postTaxFinancingCost: 0.004,
      txnCosts: 0.001,
    },
    alpha: { longAlpha: 0.004, shortAlpha: 0.004 },
    cncl: { cnclBase: 0.14, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 5_000_000,
    qualifiedPurchaserRequired: true,
  },

  // ─── Cache (Track B) ───────────────────────────────────────────────
  cache_130_30: {
    id: 'cache_130_30',
    provider: 'Cache',
    name: 'Cache 130/30',
    shortName: '130/30',
    formulaTrack: 'B',
    longRatio: 1.30,
    shortRatio: 0.30,
    grossMultiplier: 1.60,
    fees: {
      mgmtFee: 0.005,
      mgmtFeeEditable: false,
      preTaxFinancingCost: 0.003,
      postTaxFinancingCost: 0.002,
      txnCosts: 0.0008,
    },
    alpha: { longAlpha: 0.003, shortAlpha: 0.003 },
    cncl: { cnclBase: 0.08, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 1_000_000,
    qualifiedPurchaserRequired: false,
  },
  cache_200_100: {
    id: 'cache_200_100',
    provider: 'Cache',
    name: 'Cache 200/100',
    shortName: '200/100',
    formulaTrack: 'B',
    longRatio: 2.00,
    shortRatio: 1.00,
    grossMultiplier: 3.00,
    fees: {
      mgmtFee: 0.006,
      mgmtFeeEditable: false,
      preTaxFinancingCost: 0.006,
      postTaxFinancingCost: 0.004,
      txnCosts: 0.001,
    },
    alpha: { longAlpha: 0.003, shortAlpha: 0.003 },
    cncl: { cnclBase: 0.10, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 2_000_000,
    qualifiedPurchaserRequired: false,
  },
  cache_250_150: {
    id: 'cache_250_150',
    provider: 'Cache',
    name: 'Cache 250/150',
    shortName: '250/150',
    formulaTrack: 'B',
    longRatio: 2.50,
    shortRatio: 1.50,
    grossMultiplier: 4.00,
    fees: {
      mgmtFee: 0.007,
      mgmtFeeEditable: false,
      preTaxFinancingCost: 0.008,
      postTaxFinancingCost: 0.005,
      txnCosts: 0.0012,
    },
    alpha: { longAlpha: 0.003, shortAlpha: 0.003 },
    cncl: { cnclBase: 0.10, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 5_000_000,
    qualifiedPurchaserRequired: true,
  },

  // ─── Frec (Track B) ────────────────────────────────────────────────
  frec_140_40: {
    id: 'frec_140_40',
    provider: 'Frec',
    name: 'Frec 140/40',
    shortName: '140/40',
    formulaTrack: 'B',
    longRatio: 1.40,
    shortRatio: 0.40,
    grossMultiplier: 1.80,
    fees: {
      mgmtFee: 0.005,
      mgmtFeeEditable: true,
      preTaxFinancingCost: 0.004,
      postTaxFinancingCost: 0.0025,
      txnCosts: 0.0008,
    },
    alpha: { longAlpha: 0.003, shortAlpha: 0.003 },
    cncl: { cnclBase: 0.09, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 500_000,
    qualifiedPurchaserRequired: false,
  },
  frec_200_100: {
    id: 'frec_200_100',
    provider: 'Frec',
    name: 'Frec 200/100',
    shortName: '200/100',
    formulaTrack: 'B',
    longRatio: 2.00,
    shortRatio: 1.00,
    grossMultiplier: 3.00,
    fees: {
      mgmtFee: 0.006,
      mgmtFeeEditable: true,
      preTaxFinancingCost: 0.006,
      postTaxFinancingCost: 0.004,
      txnCosts: 0.001,
    },
    alpha: { longAlpha: 0.003, shortAlpha: 0.003 },
    cncl: { cnclBase: 0.10, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 1_000_000,
    qualifiedPurchaserRequired: false,
  },
  frec_250_150: {
    id: 'frec_250_150',
    provider: 'Frec',
    name: 'Frec 250/150',
    shortName: '250/150',
    formulaTrack: 'B',
    longRatio: 2.50,
    shortRatio: 1.50,
    grossMultiplier: 4.00,
    fees: {
      mgmtFee: 0.007,
      mgmtFeeEditable: true,
      preTaxFinancingCost: 0.008,
      postTaxFinancingCost: 0.005,
      txnCosts: 0.0012,
    },
    alpha: { longAlpha: 0.003, shortAlpha: 0.003 },
    cncl: { cnclBase: 0.10, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 2_500_000,
    qualifiedPurchaserRequired: true,
  },

  // ─── Parametric (Track C) ──────────────────────────────────────────
  parametric_130_30: {
    id: 'parametric_130_30',
    provider: 'Parametric',
    name: 'Parametric 130/30',
    shortName: '130/30',
    formulaTrack: 'C',
    longRatio: 1.30,
    shortRatio: 0.30,
    grossMultiplier: 1.60,
    fees: {
      mgmtFee: 0.0035,
      mgmtFeeEditable: false,
      preTaxFinancingCost: 0.003,
      postTaxFinancingCost: 0.002,
      txnCosts: 0.0005,
    },
    alpha: { longAlpha: 0.002, shortAlpha: 0.002 },
    cncl: { cnclBase: 0.07, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 250_000,
    qualifiedPurchaserRequired: false,
  },
  parametric_high_leverage: {
    id: 'parametric_high_leverage',
    provider: 'Parametric',
    name: 'Parametric High Leverage',
    shortName: 'High Lev',
    formulaTrack: 'C',
    longRatio: 2.00,
    shortRatio: 1.00,
    grossMultiplier: 3.00,
    fees: {
      mgmtFee: 0.004,
      mgmtFeeEditable: false,
      preTaxFinancingCost: 0.006,
      postTaxFinancingCost: 0.004,
      txnCosts: 0.001,
    },
    alpha: { longAlpha: 0.002, shortAlpha: 0.002 },
    cncl: { cnclBase: 0.09, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 1_000_000,
    qualifiedPurchaserRequired: false,
  },

  // ─── Neuberger Berman (Track C) ────────────────────────────────────
  neuberger_130_30: {
    id: 'neuberger_130_30',
    provider: 'Neuberger Berman',
    name: 'NB 130/30',
    shortName: '130/30',
    formulaTrack: 'C',
    longRatio: 1.30,
    shortRatio: 0.30,
    grossMultiplier: 1.60,
    fees: {
      mgmtFee: 0.004,
      mgmtFeeEditable: false,
      preTaxFinancingCost: 0.003,
      postTaxFinancingCost: 0.002,
      txnCosts: 0.0005,
    },
    alpha: { longAlpha: 0.003, shortAlpha: 0.003 },
    cncl: { cnclBase: 0.08, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 500_000,
    qualifiedPurchaserRequired: false,
    notes: 'Newer TALS offering — limited track record',
  },

  // ─── Aperio (Track C) ──────────────────────────────────────────────
  aperio_130_30: {
    id: 'aperio_130_30',
    provider: 'Aperio',
    name: 'Aperio 130/30',
    shortName: '130/30',
    formulaTrack: 'C',
    longRatio: 1.30,
    shortRatio: 0.30,
    grossMultiplier: 1.60,
    fees: {
      mgmtFee: 0.004,
      mgmtFeeEditable: false,
      preTaxFinancingCost: 0.003,
      postTaxFinancingCost: 0.002,
      txnCosts: 0.0005,
    },
    alpha: { longAlpha: 0.002, shortAlpha: 0.004 },
    cncl: { cnclBase: 0.08, decaying: false, decayRate: 0, lifetimeCap: 1.0 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 500_000,
    qualifiedPurchaserRequired: false,
  },

  // ─── Goldman Sachs (Track D) ───────────────────────────────────────
  goldman_tacs: {
    id: 'goldman_tacs',
    provider: 'Goldman Sachs',
    name: 'Goldman TACS',
    shortName: 'TACS',
    formulaTrack: 'D',
    longRatio: 1.00,
    shortRatio: 0.00,
    grossMultiplier: 1.00,
    fees: {
      mgmtFee: 0.0035,
      mgmtFeeEditable: false,
      preTaxFinancingCost: 0,
      postTaxFinancingCost: 0,
      txnCosts: 0.0003,
    },
    alpha: { longAlpha: 0, shortAlpha: 0 },
    cncl: { cnclBase: 0.12, decaying: true, decayRate: 0.15, lifetimeCap: 0.30 },
    taxLossCharacter: 'capital_gains',
    minimumInvestment: 250_000,
    qualifiedPurchaserRequired: false,
    notes: 'Long-only direct indexing. CNCL decays ~15%/yr with 30% lifetime cap.',
  },
};

export function getProviderById(id: string): ProviderStrategy | undefined {
  return PROVIDERS[id];
}

export function getProvidersByProvider(providerName: string): ProviderStrategy[] {
  return Object.values(PROVIDERS).filter((p) => p.provider === providerName);
}

export interface ProviderGroup {
  provider: string;
  strategies: ProviderStrategy[];
}

export const PROVIDER_GROUPS: ProviderGroup[] = (() => {
  const grouped = new Map<string, ProviderStrategy[]>();
  for (const strategy of Object.values(PROVIDERS)) {
    const existing = grouped.get(strategy.provider) ?? [];
    existing.push(strategy);
    grouped.set(strategy.provider, existing);
  }
  return Array.from(grouped.entries()).map(([provider, strategies]) => ({
    provider,
    strategies,
  }));
})();
