// =============================================================================
// Rollover Insight Engine — Mock Data
// =============================================================================

import type {
  RolloverPlan,
  BenchmarkEntry,
  FartherIRAFees,
  EIN,
  AmountCents,
  BasisPoints,
} from './types';

const now = new Date().toISOString();

// ==================== Mock Plans ====================

export const MOCK_PLANS: RolloverPlan[] = [
  {
    plan_id: 'plan-001',
    ein: '12-3456789' as EIN,
    plan_name: 'Acme Corp 401(k) Plan',
    sponsor_name: 'Acme Corporation',
    plan_type: 'TRADITIONAL_401K',
    plan_size_tier: 'MID',
    total_assets_cents: 4500000000 as AmountCents, // $45M
    participant_count: 850,
    plan_year_end: '2025-12-31',
    recordkeeper: 'Fidelity Investments',
    custodian: 'Fidelity',
    total_plan_expense_bps: 85 as BasisPoints,
    admin_fees_cents: 12000000 as AmountCents,
    investment_management_fees_bps: 55 as BasisPoints,
    per_participant_fee_cents: 4500 as AmountCents,
    fund_count: 28,
    index_fund_count: 8,
    target_date_fund_count: 12,
    self_directed_brokerage: true,
    roth_option: true,
    loan_provision: true,
    hardship_withdrawal: true,
    employer_stock: false,
    employer_stock_pct: 0,
    auto_enrollment: true,
    auto_escalation: true,
    data_source: 'EFAST',
    data_freshness: '2025-07-15',
    created_at: now,
    updated_at: now,
  },
  {
    plan_id: 'plan-002',
    ein: '98-7654321' as EIN,
    plan_name: 'TechStart Inc. 401(k)',
    sponsor_name: 'TechStart Inc.',
    plan_type: 'SAFE_HARBOR_401K',
    plan_size_tier: 'SMALL',
    total_assets_cents: 850000000 as AmountCents, // $8.5M
    participant_count: 120,
    plan_year_end: '2025-12-31',
    recordkeeper: 'Vanguard',
    custodian: 'Vanguard',
    total_plan_expense_bps: 42 as BasisPoints,
    admin_fees_cents: 3500000 as AmountCents,
    investment_management_fees_bps: 18 as BasisPoints,
    per_participant_fee_cents: 3200 as AmountCents,
    fund_count: 22,
    index_fund_count: 15,
    target_date_fund_count: 9,
    self_directed_brokerage: false,
    roth_option: true,
    loan_provision: true,
    hardship_withdrawal: true,
    employer_stock: false,
    employer_stock_pct: 0,
    auto_enrollment: true,
    auto_escalation: true,
    data_source: 'EFAST',
    data_freshness: '2025-06-30',
    created_at: now,
    updated_at: now,
  },
  {
    plan_id: 'plan-003',
    ein: '55-1234567' as EIN,
    plan_name: 'MegaCorp Savings Plan',
    sponsor_name: 'MegaCorp Industries',
    plan_type: 'TRADITIONAL_401K',
    plan_size_tier: 'MEGA',
    total_assets_cents: 280000000000 as AmountCents, // $2.8B
    participant_count: 45000,
    plan_year_end: '2025-12-31',
    recordkeeper: 'Empower',
    custodian: 'State Street',
    total_plan_expense_bps: 22 as BasisPoints,
    admin_fees_cents: 85000000 as AmountCents,
    investment_management_fees_bps: 8 as BasisPoints,
    per_participant_fee_cents: 2800 as AmountCents,
    fund_count: 42,
    index_fund_count: 20,
    target_date_fund_count: 14,
    self_directed_brokerage: true,
    roth_option: true,
    loan_provision: true,
    hardship_withdrawal: true,
    employer_stock: true,
    employer_stock_pct: 12,
    auto_enrollment: true,
    auto_escalation: true,
    data_source: 'EFAST',
    data_freshness: '2025-08-01',
    created_at: now,
    updated_at: now,
  },
  {
    plan_id: 'plan-004',
    ein: '33-9876543' as EIN,
    plan_name: 'Smith & Associates 401(k)',
    sponsor_name: 'Smith & Associates LLC',
    plan_type: 'SIMPLE_401K',
    plan_size_tier: 'MICRO',
    total_assets_cents: 45000000 as AmountCents, // $450K
    participant_count: 18,
    plan_year_end: '2025-12-31',
    recordkeeper: 'Principal Financial',
    custodian: 'Principal',
    total_plan_expense_bps: 145 as BasisPoints,
    admin_fees_cents: 850000 as AmountCents,
    investment_management_fees_bps: 95 as BasisPoints,
    per_participant_fee_cents: 6500 as AmountCents,
    fund_count: 14,
    index_fund_count: 3,
    target_date_fund_count: 7,
    self_directed_brokerage: false,
    roth_option: false,
    loan_provision: false,
    hardship_withdrawal: true,
    employer_stock: false,
    employer_stock_pct: 0,
    auto_enrollment: false,
    auto_escalation: false,
    data_source: 'EFAST',
    data_freshness: '2025-05-15',
    created_at: now,
    updated_at: now,
  },
  {
    plan_id: 'plan-005',
    ein: '77-5555555' as EIN,
    plan_name: 'GlobalTech Employee Savings',
    sponsor_name: 'GlobalTech Solutions',
    plan_type: 'TRADITIONAL_401K',
    plan_size_tier: 'LARGE',
    total_assets_cents: 52000000000 as AmountCents, // $520M
    participant_count: 8500,
    plan_year_end: '2025-12-31',
    recordkeeper: 'T. Rowe Price',
    custodian: 'BNY Mellon',
    total_plan_expense_bps: 38 as BasisPoints,
    admin_fees_cents: 25000000 as AmountCents,
    investment_management_fees_bps: 22 as BasisPoints,
    per_participant_fee_cents: 3500 as AmountCents,
    fund_count: 35,
    index_fund_count: 12,
    target_date_fund_count: 11,
    self_directed_brokerage: true,
    roth_option: true,
    loan_provision: true,
    hardship_withdrawal: true,
    employer_stock: true,
    employer_stock_pct: 8,
    auto_enrollment: true,
    auto_escalation: true,
    data_source: 'EFAST',
    data_freshness: '2025-07-01',
    created_at: now,
    updated_at: now,
  },
  {
    plan_id: 'plan-006',
    ein: '44-1111111' as EIN,
    plan_name: 'Regional Hospital 403(b)',
    sponsor_name: 'Regional Health System',
    plan_type: '403B',
    plan_size_tier: 'MID',
    total_assets_cents: 7800000000 as AmountCents, // $78M
    participant_count: 2200,
    plan_year_end: '2025-06-30',
    recordkeeper: 'TIAA',
    custodian: 'TIAA',
    total_plan_expense_bps: 68 as BasisPoints,
    admin_fees_cents: 8500000 as AmountCents,
    investment_management_fees_bps: 45 as BasisPoints,
    per_participant_fee_cents: 4200 as AmountCents,
    fund_count: 30,
    index_fund_count: 10,
    target_date_fund_count: 10,
    self_directed_brokerage: true,
    roth_option: true,
    loan_provision: true,
    hardship_withdrawal: false,
    employer_stock: false,
    employer_stock_pct: 0,
    auto_enrollment: true,
    auto_escalation: false,
    data_source: 'EFAST',
    data_freshness: '2025-04-15',
    created_at: now,
    updated_at: now,
  },
  {
    plan_id: 'plan-007',
    ein: '66-2222222' as EIN,
    plan_name: 'Creative Agency Profit Sharing',
    sponsor_name: 'Creative Agency Group',
    plan_type: 'PROFIT_SHARING',
    plan_size_tier: 'MICRO',
    total_assets_cents: 28000000 as AmountCents, // $280K
    participant_count: 12,
    plan_year_end: '2025-12-31',
    recordkeeper: 'John Hancock',
    custodian: 'John Hancock',
    total_plan_expense_bps: 185 as BasisPoints,
    admin_fees_cents: 450000 as AmountCents,
    investment_management_fees_bps: 125 as BasisPoints,
    per_participant_fee_cents: 7500 as AmountCents,
    fund_count: 10,
    index_fund_count: 2,
    target_date_fund_count: 5,
    self_directed_brokerage: false,
    roth_option: false,
    loan_provision: false,
    hardship_withdrawal: true,
    employer_stock: false,
    employer_stock_pct: 0,
    auto_enrollment: false,
    auto_escalation: false,
    data_source: 'EFAST',
    data_freshness: '2025-03-31',
    created_at: now,
    updated_at: now,
  },
  {
    plan_id: 'plan-008',
    ein: '88-3333333' as EIN,
    plan_name: 'University Retirement Plan',
    sponsor_name: 'State University System',
    plan_type: '403B',
    plan_size_tier: 'LARGE',
    total_assets_cents: 15000000000 as AmountCents, // $150M
    participant_count: 4200,
    plan_year_end: '2025-06-30',
    recordkeeper: 'TIAA',
    custodian: 'TIAA',
    total_plan_expense_bps: 52 as BasisPoints,
    admin_fees_cents: 15000000 as AmountCents,
    investment_management_fees_bps: 32 as BasisPoints,
    per_participant_fee_cents: 3800 as AmountCents,
    fund_count: 45,
    index_fund_count: 18,
    target_date_fund_count: 12,
    self_directed_brokerage: true,
    roth_option: true,
    loan_provision: true,
    hardship_withdrawal: false,
    employer_stock: false,
    employer_stock_pct: 0,
    auto_enrollment: true,
    auto_escalation: true,
    data_source: 'EFAST',
    data_freshness: '2025-06-15',
    created_at: now,
    updated_at: now,
  },
  {
    plan_id: 'plan-009',
    ein: '22-4444444' as EIN,
    plan_name: 'Manufacturing Co. Pension',
    sponsor_name: 'Allied Manufacturing Co.',
    plan_type: 'DEFINED_BENEFIT',
    plan_size_tier: 'MID',
    total_assets_cents: 9500000000 as AmountCents, // $95M
    participant_count: 1800,
    plan_year_end: '2025-12-31',
    recordkeeper: 'Prudential',
    custodian: 'Northern Trust',
    total_plan_expense_bps: 72 as BasisPoints,
    admin_fees_cents: 18000000 as AmountCents,
    investment_management_fees_bps: 48 as BasisPoints,
    per_participant_fee_cents: 5200 as AmountCents,
    fund_count: 0,
    index_fund_count: 0,
    target_date_fund_count: 0,
    self_directed_brokerage: false,
    roth_option: false,
    loan_provision: false,
    hardship_withdrawal: false,
    employer_stock: false,
    employer_stock_pct: 0,
    auto_enrollment: false,
    auto_escalation: false,
    data_source: 'EFAST',
    data_freshness: '2025-05-01',
    created_at: now,
    updated_at: now,
  },
  {
    plan_id: 'plan-010',
    ein: '11-5555555' as EIN,
    plan_name: 'Startup Ventures SEP IRA',
    sponsor_name: 'Startup Ventures LLC',
    plan_type: 'SEP_IRA',
    plan_size_tier: 'MICRO',
    total_assets_cents: 12000000 as AmountCents, // $120K
    participant_count: 5,
    plan_year_end: '2025-12-31',
    recordkeeper: 'Charles Schwab',
    custodian: 'Schwab',
    total_plan_expense_bps: 25 as BasisPoints,
    admin_fees_cents: 0 as AmountCents,
    investment_management_fees_bps: 8 as BasisPoints,
    per_participant_fee_cents: 0 as AmountCents,
    fund_count: 0,
    index_fund_count: 0,
    target_date_fund_count: 0,
    self_directed_brokerage: true,
    roth_option: false,
    loan_provision: false,
    hardship_withdrawal: false,
    employer_stock: false,
    employer_stock_pct: 0,
    auto_enrollment: false,
    auto_escalation: false,
    data_source: 'MANUAL',
    data_freshness: '2025-08-01',
    created_at: now,
    updated_at: now,
  },
];

// ==================== Mock Benchmarks ====================

export const MOCK_BENCHMARKS: BenchmarkEntry[] = [
  // MICRO tier benchmarks
  {
    benchmark_id: 'bench-001',
    plan_size_tier: 'MICRO',
    metric_name: 'total_plan_expense_bps',
    percentile_25: 95,
    percentile_50: 140,
    percentile_75: 185,
    percentile_90: 250,
    source: 'BrightScope/ICI 401k Fee Study 2025',
    as_of_date: '2025-06-30',
    created_at: now,
    updated_at: now,
  },
  // SMALL tier benchmarks
  {
    benchmark_id: 'bench-002',
    plan_size_tier: 'SMALL',
    metric_name: 'total_plan_expense_bps',
    percentile_25: 55,
    percentile_50: 80,
    percentile_75: 120,
    percentile_90: 165,
    source: 'BrightScope/ICI 401k Fee Study 2025',
    as_of_date: '2025-06-30',
    created_at: now,
    updated_at: now,
  },
  // MID tier benchmarks
  {
    benchmark_id: 'bench-003',
    plan_size_tier: 'MID',
    metric_name: 'total_plan_expense_bps',
    percentile_25: 35,
    percentile_50: 55,
    percentile_75: 82,
    percentile_90: 115,
    source: 'BrightScope/ICI 401k Fee Study 2025',
    as_of_date: '2025-06-30',
    created_at: now,
    updated_at: now,
  },
  // LARGE tier benchmarks
  {
    benchmark_id: 'bench-004',
    plan_size_tier: 'LARGE',
    metric_name: 'total_plan_expense_bps',
    percentile_25: 18,
    percentile_50: 32,
    percentile_75: 50,
    percentile_90: 72,
    source: 'BrightScope/ICI 401k Fee Study 2025',
    as_of_date: '2025-06-30',
    created_at: now,
    updated_at: now,
  },
  // MEGA tier benchmarks
  {
    benchmark_id: 'bench-005',
    plan_size_tier: 'MEGA',
    metric_name: 'total_plan_expense_bps',
    percentile_25: 8,
    percentile_50: 18,
    percentile_75: 30,
    percentile_90: 45,
    source: 'BrightScope/ICI 401k Fee Study 2025',
    as_of_date: '2025-06-30',
    created_at: now,
    updated_at: now,
  },
];

// ==================== Farther IRA Fee Schedule ====================

export const FARTHER_IRA_FEES: FartherIRAFees = {
  advisory_fee_bps: 50 as BasisPoints,  // 0.50%
  platform_fee_bps: 0 as BasisPoints,   // No platform fee
  average_fund_expense_bps: 5 as BasisPoints, // 0.05% (index funds)
  total_all_in_bps: 55 as BasisPoints,  // 0.55% all-in
  custodian: 'Charles Schwab',
  features: [
    'Unlimited portfolio customization',
    'Tax-loss harvesting',
    'Direct indexing (accounts > $100K)',
    'Dedicated advisor access',
    'Financial planning integration',
    'No account minimums for IRA rollovers',
    'No transaction fees on ETFs',
    'Consolidated household reporting',
    'Estate planning coordination',
    'Quarterly performance reviews',
  ],
};
